name: release

on: push

jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Build
        run: sbt publishLocal
      - name: Package
        run: mv target/scala-3.0.0/scalad_3-0.1.0.jar scalad.jar
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: scalad.jar
          path: scalad.jar
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Build
        run: sbt nativeImage
      - name: Package
        run: tar -czvf scalad-linux.tar.gz target/native-image/scalad
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: scalad-linux.tar.gz
          path: scalad-linux.tar.gz
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure git
        run: "git config --global core.autocrlf false"
        shell: bash
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Build
        shell: bash
        run: sbt nativeImage
      - name: Package
        shell: bash
        run: |
          ls -la target/native-image/scalad
          mv target/native-image/scalad scalad.exe
          tar -czvf scalad-windows.tar.gz scalad.exe
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: scalad-windows.tar.gz
          path: scalad-windows.tar.gz
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Build
        run: sbt nativeImage
      - name: Package
        run: tar -czvf scalad-macos.tar.gz target/native-image/scalad
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: scalad-macos.tar.gz
          path: scalad-macos.tar.gz
  release:
    needs: [ jar, linux, windows, macos ]
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: |
            scalad.jar
            scalad-linux.tar.gz
            scalad-windows.tar.gz
            scalad-macos.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            scalad.jar
            scalad-linux.tar.gz
            scalad-windows.tar.gz
            scalad-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
