name: release

on: push

jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Build
        run: |
          sbt publishLocal
          mv target/scala-3.0.0/scalad_3-0.1.0.jar scalad.jar
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: scalad.jar
          path: scalad.jar
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Build
        run: |
          sbt nativeImage
          tar -czvf scalad-linux.tar.gz target/native-image/scalad
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: scalad-linux.tar.gz
          path: scalad-linux.tar.gz
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Build
        run: sbt nativeImage
      - name: Package
        run: tar -czvf scalad-macos.tar.gz target/native-image/scalad
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: scalad-macos.tar.gz
          path: scalad-macos.tar.gz
  release:
    needs: [ jar, linux, macos ]
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            scalad.jar
            scalad-linux.tar.gz
            scalad-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
